image:
  registry: ghcr.io
  name: haveagitgat/tdarr
  tag: 2.32.01
keelPollSchedule: "@every 1m"
security:
  privileged: true
probes:
  liveness:
    enabled: true
    port: 8265
  startup:
    enabled: true
    port: 8265
startpage:
  icon: video
env:
  serverIP: 0.0.0.0
  serverPort: 8266
  webUIPort: 8265
  internalNode: false
  inContainer: true
  ffmpegVersion: 6
fieldEnv:
  nodeName: spec.nodeName
ports:
  ClusterIP:
  - port: 8265
    subdomain: tdarr
  LoadBalancer:
  - port: 8266
    name: server
volumes:
  persisted:
  - /app/server
  - /app/configs
  - /app/logs
  host:
  - hostPath: /lab/cache/tdarr/shows
    containerPath: /cache/shows
    type: DirectoryOrCreate
  - hostPath: /lab/cache/tdarr/movies
    containerPath: /cache/movies
    type: DirectoryOrCreate
  pvc:
  - claim: "{{ .Values.showsClaim }}"
    mounts:
      library: /library/shows
  - claim: "{{ .Values.moviesClaim }}"
    mounts:
      library: /library/movies
gpu:
  enabled: true