domain: sbnarra.me
isLive: true

loadBalancerIP: 192.168.1.11
controlPlaneIPs:
- 192.168.1.11

persistencePath: /lab/persistence

machine_ips:
  r5c: 192.168.1.1
  rx4: 192.168.1.2
  op5: 192.168.1.3
  rp4: 192.168.1.4
namespace_persistence:
  network:
    source: "{{ .Values.machine_ips.r5c }}"
  tools:
    source: "{{ .Values.machine_ips.op5 }}"
  ai:
    source: "{{ .Values.machine_ips.op5 }}"
  printer:
    source: "{{ .Values.machine_ips.op5 }}"
  starr:
    source: "{{ .Values.machine_ips.rx4 }}"
  media:
    source: "{{ .Values.machine_ips.rx4 }}"
  system:
    source: "{{ .Values.machine_ips.rp4 }}"
  smart-home:
    source: "{{ .Values.machine_ips.rp4 }}"

# keelPollSchedule: "@weekly"
keelPollSchedule: "@every 1m"

entryPoints:
- web
- websecure
middlewares:
- network-x-forwarded-https@kubernetescrd
- network-traefik-forward-auth@kubernetescrd