image:
  registry: lscr.io
  name: linuxserver/radarr
  tag: latest
probes:
  liveness:
    enabled: false
    port: 7878
    path: /ping
  startup:
    enabled: false
    port: 7878
    path: /ping
ndots: 2
ports:
  ClusterIP:
    - port: 7878
      subdomain: movies
volumes:
  persisted:
    - /config
  claims:
    - claim: "{{ .Values.mediaStorageClaim }}"
      mounts:
        /: /storage
