image:
  registry: lscr.io
  name: linuxserver/radarr
probes:
  liveness:
    enabled: false
    port: 7878
    path: /ping
  startup:
    enabled: false
    port: 7878
    path: /ping
ndots: 2
startpage:
  icon: film
ports:
  ClusterIP:
    - port: 7878
      subdomain: movies
volumes:
  persisted:
    - /config
  pvc:
  - claim: "{{ .Values.moviesClaim }}"
    mounts:
      library: /library/movies
      downloads: /downloads/movies