image:
  name: linuxserver/brave
startpage:
  icon: globe
ports:
  ClusterIP:
  - port: 3001
    subdomain: browser
    https: true
probes:
  startup:
    enabled: true
    port: 3000
volumes:
  shm:
    size: 2Gi
  persisted:
  - /config
  pvc:
  - claim: "{{ .Values.workspaceClaim }}"
    mounts:
      downloads: /downloads
gpu:
  enabled: true
security:
  privileged: true
  seccomp: Unconfined
  capabilities:
  - SYS_ADMIN