bases:
- ../../config/environments.yaml.gotmpl
- ../../modules/templates.yaml.gotmpl
---
releases:
- inherit:
  - template: deployment-storage

- name: obtr
  inherit:
  - template: stateful-deployment

- name: matter
  inherit:
  - template: stateful-deployment
  needs: [obtr]

- name: mosquitto
  inherit:
  - template: stateful-deployment

- name: zigbee
  inherit:
  - template: stateful-deployment
  needs: [mosquitto]
  labels:
    dependsOn: usbs

- name: home-assistant
  inherit:
  - template: stateful-deployment
  needs: [mosquitto, matter, obtr]

- name: nodered
  inherit:
  - template: stateful-deployment
  needs: [home-assistant]
