image:
  name: linuxserver/webtop
  tag: alpine-mate
env:
  DOCKER_MODS: linuxserver/mods:universal-package-install
  INSTALL_PACKAGES: xarchiver|curl|unzip
ports:
  ClusterIP:
  - port: 3001
    subdomain: desktop
    https: true
probes:
  startup:
    enabled: true
    port: 3000
volumes:
  shm:
    size: 2Gi
  persisted:
  - /config
  pvc:
  - claim: "{{ .Values.workspaceClaim }}"
    mounts:
      /: /workspace
gpu:
  enabled: true
security:
  privileged: true
  seccomp: Unconfined
  capabilities:
  - SYS_ADMIN