image:
  registry: lscr.io
  name: linuxserver/jellyfin
ports:
  ClusterIP:
  - port: 8096
    subdomain: media
  LoadBalancer:
  - port: 8096
    name: public
volumes:
  persisted:
  - /config
  pvc:
  - claim: "{{ .Values.showsClaim }}"
    mounts:
      library: /library/shows
  - claim: "{{ .Values.moviesClaim }}"
    mounts:
      library: /library/movies
gpu: 
  enabled: true