image:
  registry: lscr.io
  name: linuxserver/jellyfin
  tag: latest
ports:
  ClusterIP:
  - port: 8096
    subdomain: jelly
  LoadBalancer:
  - port: 8096
    name: public
volumes:
  persisted:
  - /config
  claims:
  - claim: "{{ .Values.mediaStorageClaim }}"
    mounts:
      library: /media
gpu: 
  enabled: true