image:
  registry: lscr.io
  name: linuxserver/orcaslicer
startpage:
  icon: printer
probes:
  liveness:
    enabled: true
    port: 3000
  startup:
    enabled: true
    port: 3000
ports:
  ClusterIP:
  - port: 3001
    subdomain: slicer
    https: true
volumes:
  persisted:
  - /config
  pvc:
  - claim: "{{ .Values.workspaceClaim }}"
    mounts:
      freecad: /freecad
      downloads: /downloads
gpu:
  enabled: false
affinity:
  preferred:
    default: false
  required:
    default: false
    labels:
      kubernetes.io/arch:
        values: [amd64]