image:
  registry: lscr.io
  name: linuxserver/orcaslicer
  tag: latest
probes:
  liveness:
    enabled: true
    port: 3000
  startup:
    enabled: true
    port: 3000
ports:
  ClusterIP:
  - port: 3000
    subdomain: slicer
volumes:
  persisted:
  - /config
  claims:
  - claim: "{{ .Values.sharedStorageClaim }}"
    mounts:
      freecad: /freecad
      downloads: /downloads
gpu:
  enabled: true
affinity:
  preferred:
    default: false
  required:
    default: false
    labels:
      kubernetes.io/arch:
        values: [amd64]