image:
  registry: lscr.io
  name: linuxserver/bazarr
probes:
  liveness:
    enabled: true
    port: 6767
  startup:
    enabled: true
    port: 6767
startpage:
  icon: message-square
ports:
  ClusterIP:
    - port: 6767
      subdomain: subtitles
volumes:
  persisted:
    - /config
  pvc:
  - claim: "{{ .Values.showsClaim }}"
    mounts:
      library: /library/shows
  - claim: "{{ .Values.moviesClaim }}"
    mounts:
      library: /library/movies