image:
  registry: lscr.io
  name: linuxserver/homeassistant
  tag: latest
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet
deploymentStrategy: Recreate
env:
  DOCKER_MODS: linuxserver/mods:homeassistant-hacs
liveness:
  port: 8123
ports:
  ClusterIP:
  - port: 8123
    subdomain: ha
    unprotected: true
  LoadBalancer:
  - port: 1400
    name: sonos
volumes:
  persisted:
  - /config
  # config:
  # - path: /config/configuration.yaml
  #   content: >-
  #     {{ tpl (.Files.Get "configmap/configuration.yaml") . }}
  host:
  - hostPath: /etc/localtime
    containerPath: /etc/localtime
    type: File
  - hostPath: /etc/timezone
    containerPath: /etc/timezone
    type: File
  - hostPath: /run/dbus
    containerPath: /run/dbus
    type: Directory
security:
  privileged: true
