image:
  registry: ghcr.io
  name: home-assistant-libs/python-matter-server
  tag: stable
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet
security:
  privileged: true
  seccomp: Unconfined
ports:
  ClusterIP:
  - port: 5580
volumes:
  persisted:
  - /data