insecureRegistry: true
exports:
  standard:
    type: deployment
    image:
      registry: null
      name: null
      tag: latest
      pullPolicy: IfNotPresent
    labels: {}
    deploymentStrategy: RollingUpdate
    probes:
      liveness:
        enabled: false
        path: /
        port: web
        delay: 10
        interval: 30
        timeout: 15
        threshold: 4
        headers: {}
      startup:
        enabled: false
        path: /
        port: web
        delay: 10
        interval: 10
        timeout: 10
        threshold: 8
        headers: {}
    replicas: 1
    hostNetwork: false
    affinity:
      required: 
        default: true
        labels: {}
        # kubernetes.io/arch:
          # values: [amd64]
      preferred: 
        default: true
        labels: {}
        # kubernetes.io/arch:
          # weight: 60
          # values: [amd64]
    env: {}
    secretEnv: {}
    args: []
    command: []
    gpu:
      enabled: false
      user: abc # linuxserver specific by default
    startpage:
      icon: link
    ports: {}
      # ClusterIP:
      #   - port: 80
      #     protocol: TCP
      #     subdomain: app-name
      #     name: port-name
      #     unprotected: false
      # LoadBalancer:
      #   - port: 8080
      #     name: port-name
      #     protocol: TCP
    volumes:
      shm:
        size: "0"
      persisted: []
        # - /var
        # - /opt
      pvc: []
        # - claim: xxx
        #   mounts:
        #    - /hostSubPath: /containerPath
      secret: []
        #  - path: /home/user/.ssh/id_ecdsa.pub
        #    content: somesecretfilecontents
        #    mode: "0700"
      config: []
        # - path: /etc/service.rc
        #   content: someconfigcontents OR dir: configmap
        #   mode: "0700"
      host: []
        # - hostPath: /hostPath
        #   containerPath: /containerPath
        #   type: https://kubernetes.io/docs/concepts/storage/volumes/#hostpath-volume-types
    security:
      privileged: false
      seccomp: null
      capabilities: []
        # - "NET_ADMIN"
        # - "SYS_MODULE"
      sysctls: {}
        # net.ipv4.conf.all.src_valid_mark: "1"

    ##Â CronJob
    # schedule: "* * * * *"
    # scheduleDisabled: true
