image:
  registry: lscr.io
  name: linuxserver/freecad
startpage:
  icon: codesandbox
probes:
  liveness:
    enabled: true
    port: 3000
  startup:
    enabled: true
    port: 3000
ports:
  ClusterIP:
  - port: 3000
    subdomain: cad
volumes:
  persisted:
  - /config
  pvc:
  - claim: "{{ .Values.workspaceClaim }}"
    mounts:
      freecad: /freecad
gpu:
  enabled: true